<a href="https://colab.research.google.com/github/MingzheHu-Duke/BrownELVO/blob/main/Brown_Map_keys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import chardet
import pandas as pd

In [4]:
# Read in the elvo keys
with open('/content/train_elvo_detection_kfold_with_original_accessions.csv', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large


df_keys = pd.read_csv('/content/train_elvo_detection_kfold_with_original_accessions.csv', encoding=result['encoding'])
df_keys.head(10)

   accession                                            imgfile  ...  inner3  inner4
0   53279534  numpy-recreated-mips-from-thins/ccff23f51fd707...  ...       4       4
1   52608888  numpy-recreated-mips-from-thins/5069cf7b6ed8b1...  ...       8     888
2   52853439  numpy-recreated-mips-from-thins/b26972bedccdd0...  ...       1       8
3   53195739  numpy-recreated-mips-from-thins/ad8a2c06ddb0ba...  ...       8     888
4   52818203  numpy-recreated-mips-from-thins/7a603e8495ee65...  ...       2       1
5   52955037  numpy-recreated-mips-from-thins/796322bdae29c9...  ...       5       8
6   53141791  numpy-recreated-mips-from-thins/41b79343c201e1...  ...       8       2
7   53312481  numpy-recreated-mips-from-thins/92dea73747f54c...  ...       9     888
8   51386110  numpy-recreated-mips-from-thins/11058fe1a5ef99...  ...       2       5
9   53209118  numpy-recreated-mips-from-thins/c43075e580c4f6...  ...     888       8

[10 rows x 9 columns]

In [5]:
# Read in the clinical info
df_info = pd.read_excel('/content/BROWN急慢性判断ELVO_official.xlsx')
df_info.head(10)

  Organization  ... Total (Technical) (RVU)
0          RIH  ...                   11.58
1          RIH  ...                   11.58
2          NPH  ...                   11.58
3          TMH  ...                   11.58
4          RIH  ...                   11.58
5          TMH  ...                   11.58
6          RIH  ...                   11.58
7          RIH  ...                   11.58
8          RIH  ...                     NaN
9          TMH  ...                   11.58

[10 rows x 83 columns]

In [7]:
# Find the maps between the Sham Accession number and the accession number
df_maps = df_keys[["accession"]]
# Peek
df_maps.head()

   accession
0   53279534
1   52608888
2   52853439
3   53195739
4   52818203

In [11]:
# Left Merge to extract the info
df_merged = df_maps.merge(df_info, left_on="accession", right_on="Accession Number")

In [12]:
print("Len of extracted clinical info:" +str(len(df_merged)))
print("Len of keys:" +str(len(df_keys)))
print("Len of original Brown exel:" +str(len(df_info)))

Len of extracted clinical info:8650
Len of keys:8650
Len of original Brown exel:9005

In [13]:
# Save the data frameinto csv file
df_merged.to_csv ('extracted_clinical_info.csv', index = False, header=True)